Update Wireguard_Script

diff --git a/Wireguard_Script b/Wireguard_Script
--- a/Wireguard_Script
+++ b/Wireguard_Script
@@ -25,7 +25,6 @@ is_valid_ip() {
 while true; do
     # Input from user
     read -p $'\nChoose the install type:\n\n1. (OPTIONAL) Set Static IP\n2. Wireguard Server\nType "exit" to exit the script: ' install_type
-    
     case "$install_type" in
         1)
             echo -e "\n***WARNING***\nOnce you change the IP, you WILL be disconnected.\nYou will need to re-connect using the correct IP.\n"
@@ -44,14 +43,18 @@ while true; do
                 read -p "Input the static IP with CIDR (e.g. 192.168.0.1/24): " static_ip
                 read -p "Are you sure you want to use "$static_ip"? y/n: " static_confirm
                 if [[ $static_confirm = y ]]; then
-                    sed -i "/address/c\        address "$static_ip" " $net_int
-                    break
+                    if sed -i "/address/c\        address "$static_ip" " $net_int; then
+                        echo "Address has been changed."
+                        break
+                    else
+                        echo "Failed to change address. Please make sure dhcp is on the correct line."
+                        exit 1
+                    fi
                 elif [[ $static_confirm = n ]]; then
                     echo "Please try again."
                 else
                     echo "not a valid answer. Please use \"y\" or \"n\"."
-                fi
-                echo "Address has been changed."
+                fi 
             done
 
             # Edits the Gateway
@@ -59,15 +62,19 @@ while true; do
                 read -p "Input the gateway: " static_gw
                 read -p "Are you sure you want to use "$static_gw"? y/n: " static_gw_confirm
                 if [[ $static_gw_confirm = y ]]; then
-                    sed -i "/gateway/c\        gateway "$static_gw" " $net_int
-                    break
+                    if sed -i "/gateway/c\        gateway "$static_gw" " $net_int; then
+                        echo "Gateway has been changed."
+                        break
+                    else
+                        echo "Failed to change Gateway. Please make sure dhcp is on the correct line."
+                        exit 1
+                    fi
                 elif [[ $static_gw_confirm = n ]]; then
                     echo "Please try again."
                 else
                     echo "not a valid answer. Please use \"y\" or \"n\"."
                 fi
-                echo "Gateway has been changed."
-            done       
+            done
             echo -e "Network settings have been updated, and network has been refreshed.\nPlease connect using the new IP\nExiting script."
             systemctl restart networking
             ;;
