Update Wireguard_Script

diff --git a/Wireguard_Script b/Wireguard_Script
--- a/Wireguard_Script
+++ b/Wireguard_Script
@@ -41,7 +41,7 @@ while true; do
 
             # Edits the IP
             while true; do
-                read -p "Input the static IP with CIDR (e.g. 192.168.0.1/24): " static_ip
+                read -p "Input the static IP you would like to use. (e.g. 192.168.0.1): " static_ip
                 read -p "Are you sure you want to use "$static_ip"? y/n: " static_confirm
                 if [[ $static_confirm = y ]]; then
                     if grep -q address $net_int; then
@@ -53,6 +53,26 @@ while true; do
                         exit 1
                     fi
                 elif [[ $static_confirm = n ]]; then
+                    echo "Please try again."
+                else
+                    echo "not a valid answer. Please use \"y\" or \"n\"."
+                fi 
+            done
+
+            # Adds the CIDR notation to the end of the IP.
+            while true; do
+                read -p "Whats the subnet mash in CIDR notation? (e.g. \/24)": " cidr_input
+                read -p "Are you sure you want to use "$cidr_input"? y/n: " cidr_confirm
+                if [[ $cidr_confirm = y ]]; then
+                    if grep -q "$static_ip" $net_int; then
+                        sed -i "/$static_ip/c\        address "$static_ip""$cidr_input" " $net_int \
+                        && echo "Subnet has been added."
+                        break
+                    else
+                        echo -e "Failed to change subnet. Please make sure dhcp is on the correct line.\nExiting Script."
+                        exit 1
+                    fi
+                elif [[ $cidr_confirm = n ]]; then
                     echo "Please try again."
                 else
                     echo "not a valid answer. Please use \"y\" or \"n\"."
