Update Wireguard_Script

diff --git a/Wireguard_Script b/Wireguard_Script
--- a/Wireguard_Script
+++ b/Wireguard_Script
@@ -59,7 +59,8 @@ while true; do
     # Input from user
     read -p $'\nChoose the install type:\n\n1. (OPTIONAL) Set Static IP\n2. Wireguard Server\n3. Wireguard Server Peer Config\nType "exit" to exit the script: ' install_type
     case "$install_type" in
-        1)
+        1) 
+			# Static IP configuration
             echo -e "\n***WARNING***\nOnce you change the IP, you WILL be disconnected.\nYou will need to re-connect using the correct IP.\n"
 
             # checks to see if network is DHCP, then changes it to static and adds address and gateway.
@@ -147,7 +148,8 @@ while true; do
             exit 1
             ;;
         2)
-            echo -e "Starting the installation of the Wireguard server...\nStarting update and upgrade for this machine..."
+            # Wireguard Server Install and Setup
+			echo -e "Starting the installation of the Wireguard server...\nStarting update and upgrade for this machine..."
             apt update &> /dev/null && apt upgrade -y &> /dev/null
             echo "apt update and apt upgrade have completed."
 
@@ -223,47 +225,68 @@ EOF
             break # Exit the loop
             ;;
         3)
-	    # Start of the config for peers for the Server
-	    echo "What would you like to do?"
-	    read -p $'\n1. Add a new Peer.\n2. Remove a Peer.\n3. Edit a Peer.\n4. Exit back to the main menu\n: ' peer_choice
-	    while true; do
-		case "$peer_choice" in
-			1) # Add a Peer
-				read -p $'Enter a name for the peer\n: ' peer_name
-			    	read -p $'Enter the IP for the peer to use\n: ' peer_ip
-			    	read -p $'Enter the public key from the client peer\n: ' peer_key
+	    	# Start of the config for peers for the Server
+	    	echo "What would you like to do?"
+	    	while true; do
+			read -p $'\n1. Add a new Peer.\n2. Remove a Peer.\n3. Edit a Peer.\n4. Exit back to the main menu\n: ' peer_choice
+				case "$peer_choice" in
+					1)
+						# Add a Peer
+						read -p $'Enter a name for the peer\n: ' peer_name
+			    		read -p $'Enter the IP for the peer to use\n: ' peer_ip
+			    		read -p $'Enter the public key from the client peer\n: ' peer_key
 	
-				invalid_input=false
+						invalid_input=false
 	
-				if ! is_valid_ip "$peer_ip"; then
-					echo "'$peer_ip' is not a valid IP Address."
-					invalid_input=true
-				fi
+						if ! is_valid_ip "$peer_ip"; then
+							echo "'$peer_ip' is not a valid IP Address."
+							invalid_input=true
+						fi
 	
-				if ! key_check "$peer_key"; then
-					echo "'$peer_key' is not a valid public key."
-					invalid_input=true
-				fi
+						if ! key_check "$peer_key"; then
+							echo "'$peer_key' is not a valid public key."
+							invalid_input=true
+						fi
 	
-				if [[ "$invalid_input" == false ]]; then
-					cat <<EOF >> /etc/wireguard/wg0.conf
+						if [[ "$invalid_input" == false ]]; then
+							cat <<EOF >> /etc/wireguard/wg0.conf
 [Peer]
 # $peer_name
 PublicKey = $peer_key
 AllowedIPs = $peer_ip/32
 EOF
+							echo "Peer added successfully."
+						else
+							echo "Input not valid. Please double check your input."
+						fi
+						;;
+					2)
+						while true; do
+							# Delete a Peer
 
-					echo "Peer added successfully."
-				else
-					echo "Input not valid. Please double check your input."
-				fi
-				;;
-			4) # Exit
-				echo "Exiting the peer configuration menu."
-				break
-				;;
-		esac
-	    done
+							# List the peers
+							awk -F' = |# ' '/#/{name=$2} /AllowedIPs/{print name, $2}' /etc/wireguard/wg0.conf
+
+							# Ask the user which peer they would like to select
+							read -p $'Which user would you like to delete?\n: ' user_select
+								if grep -q "# $user_select" /etc/wireguard/wg0.conf; then
+									sed -i '/\[Peer\]/ { N; /\n# $user_select/ { N; N; d; } }' /etc/wireguard/wg0.conf
+									sed -i '/^$/N;/^\n$/D' /etc/wireguard/wg0.conf
+									echo "User '$user_select' deleted."
+									break
+								else
+									echo "User not found, please try again."
+								fi
+						done
+						;;
+					4)
+						# Exit
+						echo "Exiting the peer configuration menu."
+						break
+						;;
+				esac
+	    	done
+			;;
 	exit)
             echo "The script will now exit."
             break
