Update Wireguard_Script

diff --git a/Wireguard_Script b/Wireguard_Script
--- a/Wireguard_Script
+++ b/Wireguard_Script
@@ -33,14 +33,14 @@ cidr_check() {
 check_install() {
     local install_name="$1"
 	echo "looking for $install_name..."
-    	if ! command -v "$install_name" &> /dev/null; then
+    if ! command -v "$install_name" &> /dev/null; then
 	    echo "Installing $install_name..."
 	    apt install $install_name -y &> /dev/null
 	    if command -v "$install_name" &> /dev/null; then
-		echo "$install_name has been successfully installed."
+		    echo "$install_name has been successfully installed."
 	    else
-		echo "Installation failed. Please clear the error and try again."
-		exit 1
+		    echo "Installation failed. Please clear the error and try again."
+		    exit 1
 	    fi
 	else
 	    echo "$install_name is already installed. Continuing..."
