Update Wireguard_Script

diff --git a/Wireguard_Script b/Wireguard_Script
--- a/Wireguard_Script
+++ b/Wireguard_Script
@@ -70,7 +70,7 @@ while true; do
     # Input from user
     read -p $'\nChoose the install type:\n\n1. (OPTIONAL) Set Static IP\n2. Wireguard Server Setup\n3. Wireguard Server Peer Config\n4. Client Peer Setup\n5. Client Peer Config\n7. Delete and cleanup\nType "exit" to exit the script\n: ' install_type
     case "$install_type" in
-        1) 
+        1)
 			# Static IP configuration
             echo -e "\n***WARNING***\nOnce you change the IP, you WILL be disconnected.\nYou will need to re-connect using the correct IP.\n"
 
@@ -85,23 +85,26 @@ while true; do
 
             # Edits the IP
             while true; do
-                read -p "Input the static IP you would like to use. (e.g. 192.168.0.1): " static_ip
-                read -p "Are you sure you want to use "$static_ip"? y/n: " static_confirm
+                read -p $'Input the static IP you would like the Wireguard Server to use. (e.g. 192.168.1.2)\n: ' static_ip
                 if is_valid_ip "$static_ip"; then
-                    if [[ $static_confirm == y ]]; then
-                        if grep -q address $net_int; then
-                            sed -i "/address/c\        address "$static_ip" " $net_int \
-                            && echo "Address has been changed."
+                    while true; do
+                        read -p $'Are you sure you want to use "$static_ip"? y/n\n: ' static_confirm
+                        if [[ $static_confirm == y ]]; then
+                            if grep -q address $net_int; then
+                                sed -i "/address/c\        address "$static_ip" " $net_int \
+                                && echo "Address has been changed."
+                                break 2
+                            else
+                                echo -e "Failed to change address. Please make sure dhcp is on the correct line.\nExiting Script."
+                                exit 1
+                            fi
+                        elif [[ $static_confirm == n ]]; then
+                            echo "Please try again."
                             break
                         else
-                            echo -e "Failed to change address. Please make sure dhcp is on the correct line.\nExiting Script."
-                            exit 1
+                            echo "not a valid answer. Please use \"y\" or \"n\"."
                         fi
-                    elif [[ $static_confirm == n ]]; then
-                        echo "Please try again."
-                    else
-                        echo "not a valid answer. Please use \"y\" or \"n\"."
-                    fi
+                    done
                 else
                     echo "not a valid IP. Please enter a valid IP."
                 fi
@@ -109,23 +112,25 @@ while true; do
 
             # Adds the CIDR notation to the end of the IP.
             while true; do
-                read -p "Enter the subnet in CIDR notation. (e.g. 24): " cidr_input
-                read -p "Are you sure you want to use "$cidr_input"? y/n: " cidr_confirm
+                read -p $'Enter the subnet in CIDR notation. (e.g. 24)\n: ' cidr_input
                 if cidr_check "$cidr_input"; then
-                    if [[ $cidr_confirm == y ]]; then
-                        if grep -q "$static_ip" $net_int; then
-                            sed -i "/"$static_ip"/c\        address "$static_ip"\/"$cidr_input" " $net_int \
-                            && echo "Subnet has been added."
-                            break
+                    while true; do
+                        read -p $'Are you sure you want to use "$cidr_input"? y/n\n: ' cidr_confirm
+                        if [[ $cidr_confirm == y ]]; then
+                            if grep -q "$static_ip" $net_int; then
+                                sed -i "/"$static_ip"/c\        address "$static_ip"\/"$cidr_input" " $net_int \
+                                && echo "Subnet has been added."
+                                break 2
+                            else
+                                echo -e "Failed to change subnet. Please make sure dhcp is on the correct line.\nExiting Script."
+                                exit 1
+                            fi
+                        elif [[ $cidr_confirm == n ]]; then
+                            echo "Please try again."
                         else
-                            echo -e "Failed to change subnet. Please make sure dhcp is on the correct line.\nExiting Script."
-                            exit 1
+                            echo "not a valid answer. Please use \"y\" or \"n\"."
                         fi
-                    elif [[ $cidr_confirm == n ]]; then
-                        echo "Please try again."
-                    else
-                        echo "not a valid answer. Please use \"y\" or \"n\"."
-                    fi
+                    done
                 else
                     echo "Not a valid input. Please choose a number 0-32."
                 fi
@@ -133,23 +138,25 @@ while true; do
 
             # Edits the Gateway
             while true; do
-                read -p "Input the gateway: " static_gw
-                read -p "Are you sure you want to use "$static_gw"? y/n: " static_gw_confirm
-                if is_valid_ip "$static_gw"; then   
-                    if [[ $static_gw_confirm = y ]]; then
-                        if grep -q address $net_int; then
-                            sed -i "/gateway/c\        gateway "$static_gw" " $net_int \
-                            && echo "Gateway has been changed."
-                            break
+                read -p $'Input the gateway\n: ' static_gw
+                if is_valid_ip "$static_gw"; then
+                    while true; do
+                        read -p $'Are you sure you want to use "$static_gw"? y/n\n: ' static_gw_confirm
+                        if [[ $static_gw_confirm = y ]]; then
+                            if grep -q address $net_int; then
+                                sed -i "/gateway/c\        gateway "$static_gw" " $net_int \
+                                && echo "Gateway has been changed."
+                                break 2
+                            else
+                                echo -e "Failed to change Gateway. Please make sure dhcp is on the correct line.\nExiting Script."
+                                exit 1
+                            fi
+                        elif [[ $static_gw_confirm = n ]]; then
+                            echo "Please try again."
                         else
-                            echo -e "Failed to change Gateway. Please make sure dhcp is on the correct line.\nExiting Script."
-                            exit 1
+                            echo "not a valid answer. Please use \"y\" or \"n\"."
                         fi
-                    elif [[ $static_gw_confirm = n ]]; then
-                        echo "Please try again."
-                    else
-                        echo "not a valid answer. Please use \"y\" or \"n\"."
-                    fi
+                    done
                 else
                     echo "not a valid IP. Please enter a valid IP."
                 fi
@@ -251,7 +258,7 @@ EOF
 	    
 	    while true; do
             if grep -q '^EndPoint' /etc/wireguard/wg0.conf; then
-                echo -e "\n **WARNING** This config file is set up to be a Peer. Please run the \"Client\" Peer Config option instead."
+                echo -e "\n **WARNING** This config file is set up to be a Peer. Please run the \"Client Peer Config\" option instead."
                 break
             fi
 
@@ -324,7 +331,7 @@ EOF
 			    	
                 # Ask the user which peer they would like to select
                 while true; do
-			    	read -p $'\nWhich user would you like to delete?\n: ' user_select
+			    	read -p $'\nWhich user would you like to delete? (case sensitive)\n: ' user_select
 			    	if grep -q "# $user_select" /etc/wireguard/wg0.conf; then
 						sed -i "/\[Peer\]/ { N; /\n# $user_select/ { N; N; d; } }" /etc/wireguard/wg0.conf
 						sed -i '/^$/N;/^\n$/D' /etc/wireguard/wg0.conf
@@ -349,7 +356,7 @@ EOF
 
                 while true; do
 				    # User choice to edit
-					read -p $'\nWhich user would you like to edit?\n: ' user_select2
+					read -p $'\nWhich user would you like to edit? (case sensitive)\n: ' user_select2
 					if grep -q "# $user_select2" /etc/wireguard/wg0.conf; then
 						read -p $'Which setting would you like to edit?\n\n1. Change the Public Key\n2. Change the users IP\n3. Exit back to the previous menu\n: ' setting_select
 						case "$setting_select" in
@@ -358,7 +365,7 @@ EOF
                                     read -p $'Please enter the Public Key you would like to use\n: ' new_public_key
 								    # change the public key
 								    if key_check "$new_public_key"; then
-                                        sed -i "/# $user_select2/,/^\[Peer\]/ { s/^PublicKey =.*/PublicKey = ${new_public_key} }" /etc/wireguard/wg0.conf
+                                        sed -i "/# $user_select2/,/^\[Peer\]/ { s|^PublicKey =.*|PublicKey = ${new_public_key}| }" /etc/wireguard/wg0.conf
 								        echo "Public Key has been changed. Restarting Wireguard..." \
                                         && systemctl restart wg-quick@wg0.service
 								        break
@@ -404,9 +411,7 @@ EOF
         ;;
         4)
             # Checks to see if the config file is already there, if it is, it will break.
-			if [ ! -f /etc/wireguard/wg0.conf ]; then
-                :
-            else
+			if [ -f /etc/wireguard/wg0.conf ]; then
                 echo " **WARNING** Wireguard config found, please run the cleanup option if you need to reinstall."
                 continue
             fi
@@ -457,7 +462,7 @@ EOF
             done
 
             while true; do
-                read -p $'Please enter the Allowed Network (0.0.0.0 is full tunnel)\n: ' allowed_ips_peer
+                read -p $'Please enter the Allowed Network (Note: 0.0.0.0 is full tunnel. Please use a 0 in the 4th octet)\n: ' allowed_ips_peer
                 if is_valid_ip "$allowed_ips_peer"; then
                     break
                 else
@@ -466,7 +471,7 @@ EOF
             done
 
             while true; do
-                read -p $'Please enter the CIDR of your Allowed IP\n: ' allowed_ip_cidr
+                read -p $'Please enter the CIDR of your Allowed Network\n: ' allowed_ip_cidr
                 if cidr_check "$allowed_ip_cidr"; then
                     break
                 else
@@ -529,11 +534,11 @@ EOF
                 fi
 
                 if grep -q '^PreUp' /etc/wireguard/wg0.conf; then
-                    echo -e "\n **WARNING** This config file is set up to be a Server. Please run the \"Server\" Setup option instead."
+                    echo -e "\n **WARNING** This config file is set up to be a Server. Please run the \"Wireguard Server Peer Config\" option instead."
                     break
                 fi
 
-                read -p $'\nChoose which option you would like to edit\n\n1. Edit the peer address\n2. Edit the remote Wireguard Public Key\n3. Edit Allowed IPs\n4. Edit the IP and port of the EndPoint. (Remote WG WAN and port)\n5. Exit to the previous menu\n: ' client_input
+                read -p $'\nChoose which option you would like to edit\n\n1. Edit the peer address\n2. Edit the remote Wireguard Public Key\n3. Edit Allowed Networks\n4. Edit the IP and port of the EndPoint. (Remote WG WAN and port)\n5. Exit to the previous menu\n: ' client_input
                 case "$client_input" in
                     1)
                         # Edit the IP Address
@@ -570,11 +575,12 @@ EOF
                         done
                     ;;
                     3)
-                        # Edit Allowed IP's
+                        # Edit Allowed Networks's
                         while true; do
                             echo -e "\nHere is a list of the networks that are allowed for this Peer (0.0.0.0/0 is default and means a full tunnel connection):\n"
                             grep '^AllowedIPs' /etc/wireguard/wg0.conf
-                            read -p $'\n1. Change the network of AllowedIPs (This will change the line back to one network allowed.)\n2. Append a new network to end of the AllowedIP list\n3. Exit to the previous menu\n: ' allowed_input
+                            echo -e "\nNOTE: Please use a 0 in the 4th octet"
+                            read -p $'1. Change the network of AllowedIPs (This will change the line back to one network allowed.)\n2. Append a new network to end of the AllowedIP list\n3. Exit to the previous menu\n: ' allowed_input
                             case "$allowed_input" in
                                 1)
                                     # Change the IP
@@ -634,7 +640,7 @@ EOF
                     4)
                         # Edit the WAN of the remote Wireguard server this Peer is connecting to
                         while true; do
-                            echo -e "\nHere is the WAN IP and port of the remote Wireguard server this peer connects to:"
+                            echo -e "\nHere is the WAN IP and port of the remote Wireguard Server this peer connects to:"
                             grep '^EndPoint' /etc/wireguard/wg0.conf
 							read -p $'\n1. Change the Remote WG Server IP (This is the IP used to communicate to the remote Wireguard Server)\n2. Change the port\n3. Exit to the previous menu\n: ' wan_peer_input
                             case "$wan_peer_input" in
